version: '2'

services:
  app:
    build: .
    volumes:
      - .:/app
    volumes_from:
      - secrets:ro
    environment:
      DB_HOST: 'postgres'
      DB_DATABASE: 'postgres'
      DB_USER: 'postgres'
      STATSD_HOST: 'statsd'

  secrets:
    image: turistforeningen/postgis-active-connections-secrets:v1
    volumes:
      - /secrets
